name: EliteBossEvent
version: '${project.version}'
main: com.pinont.elitebossevent.EliteBossEvent
api-version: '1.20'
depend:
    - MythicMobs

commands:
    eliteboss:
        description: EliteBossEvent command
        permission: ebe.use
        usage: /elitebossevent
        aliases: [ebe]

permissions:
    ebe.admin:
        description: EliteBossEvent admin permission
        parent: [ebe.use, ebe.bypass, ebe.notify]

    ebe.use:
        description: EliteBossEvent use permission
        default: true

    ebe.bypass:
        description: EliteBossEvent bypass permission

    ebe.notify:
        description: EliteBossEvent notify permission

    ebe.debug:
        description: EliteBossEvent debug permission
